<a href="https://colab.research.google.com/github/TTamyy/Machine-Learning/blob/Cross_Validation/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

import numpy as np
from sklearn.model_selection import LeaveOneOut


X = np.array([[1, 2], [3, 4],[5,6],[8,9]])
y = np.array([1, 2,1,2])

#USING LEAVE ONE OUT -> TRAIN N-1 SAMPLES, TEST 1 SAMPLE
loo = LeaveOneOut()
loo.get_n_splits(X)

print(loo)

for train_index, test_index in loo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test, y_train, y_test)


LeaveOneOut()
TRAIN: [1 2 3] TEST: [0]
[[3 4]
 [5 6]
 [8 9]] [[1 2]] [2 1 2] [1]
TRAIN: [0 2 3] TEST: [1]
[[1 2]
 [5 6]
 [8 9]] [[3 4]] [1 1 2] [2]
TRAIN: [0 1 3] TEST: [2]
[[1 2]
 [3 4]
 [8 9]] [[5 6]] [1 2 2] [1]
TRAIN: [0 1 2] TEST: [3]
[[1 2]
 [3 4]
 [5 6]] [[8 9]] [1 2 1] [2]


In [34]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[1,2]])
y = np.array([0, 0, 1, 1,0])

#Each set contains approximately the same percentage of samples of each target class as the complete set.
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)

for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test, y_train, y_test)


StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [3 4] TEST: [0 1 2]
[[3 4]
 [1 2]] [[1 2]
 [3 4]
 [1 2]] [1 0] [0 0 1]
TRAIN: [0 1 2] TEST: [3 4]
[[1 2]
 [3 4]
 [1 2]] [[3 4]
 [1 2]] [0 0 1] [1 0]
